site_name: 'python-app-4'
site_description: 'Main documentation for python-app-4'
repo_url: https://github.com/minhpham95/python-app-4
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'docs/index.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting Started: 'docs/index.md'
      - Architecture overview: 'docs/index.md'
      - Project Roadmap: 'docs/index.md'
      - Vision: 'docs/index.md'